#Port
server.port=8085
#spring.profiles.active=qa

# server.servlet.context-path=/api/EwayMotorApi
server.forward-headers-strategy=framework
springdoc.swagger-ui.use-root-path=true

 spring.datasource.url = jdbc:mysql://192.168.1.9:3306/ewayglobal?useSSL=false
 spring.datasource.username = MSDB
 spring.datasource.password = Admin
 
#spring.datasource.url = jdbc:mysql://phoenix.ch2um48w2qs0.ap-south-1.rds.amazonaws.com:3306/phoenixwecorelive?useSSL=false
#spring.datasource.username=admin
#spring.datasource.password=pYvvdEDQ4hkR4bqdlkJc


#spring.datasource.url = jdbc:mysql://phoenix.ch2um48w2qs0.ap-south-1.rds.amazonaws.com:3306/wecorelive?useSSL=false
#spring.datasource.username=admin
#spring.datasource.password=pYvvdEDQ4hkR4bqdlkJc

#spring.datasource.url = jdbc:mysql://3.6.61.228:3306/ewayglobal?useSSL=false
#spring.datasource.username = root
#spring.datasource.password = P@Nn!Y!NS3LV@n@1

#spring.datasource.url = jdbc:mysql://193.203.162.152:3306/ewayglobal?useSSL=false
#spring.datasource.username = root
#spring.datasource.password = Y0(EH#CQV)Ur

#spring.datasource.url = jdbc:mysql://phoenix.ch2um48w2qs0.ap-south-1.rds.amazonaws.com:3306/wecorelive
#spring.datasource.username=admin
#spring.datasource.password=pYvvdEDQ4hkR4bqdlkJc

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.dbcp2.maxActive=1
spring.datasource.dbcp2.max-idle=1
spring.batch.jdbc.initialize-schema = ALWAYS
spring.jpa.show-sql=true
#spring.jpa.properties.javax.persistence.query.timeout=5000
spring.jpa.properties.jakarta.persistence.query.timeout=50000
spring.main.allow-bean-definition-overriding=true
spring.datasource.hikari.auto-commit=true
spring.datasource.dbcp2.default-auto-commit=true
spring.main.allow-circular-references=true
spring.datasource.dbcp2.max-total=2
spring.datasource.dbcp2.remove-abandoned-timeout=1000000

#linkcalc
calc.section=http://localhost:8086/calculator/calc/call

jasper.datasourceby.jndi=N
#spring.datasource.jndi-name=java:comp/env/claimApi

# Swaggger
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

#Common Path Details
#file.directoryPath=D:\\Document\\OrginalPath\\
#file.backuppath=D:\\Document\\BackupPath\\
file.directoryPath=\\\\192.168.1.99\\Users\\CommonPath\\EwayPortal\\OrginalPath\\
file.compressedImg=\\\\192.168.1.99\\Users\\CommonPath\\EwayPortal\\CompressedImg\\
file.backuppath=\\\\192.168.1.99\\Users\\CommonPath\\EwayPortal\\BackupPath\\
file.primaryPath=\\\\192.168.1.99\\Users\\CommonPath\\EwayPortal\\

#Multi Part File Size
spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=6MB

# External Api Call
MotorVerificationV1Link=https://api.tira.go.tz:8091/dispatch/api/motor/verification/v1/request
MotorPostingV1Link=https://api.tira.go.tz:8091/ecovernote/api/covernote/non-life/motor/v2/request

FleetMotorPostingV1Link=https://api.tira.go.tz:8091/ecovernote/api/covernote/non-life/motor-fleet/v2/request
CoverNoteVerificationLink=https://api.tira.go.tz:8091/ecovernote/api/covernote/verification/min/v1/request
HeadearAdd1Key=ClientCode
HeadearAdd1Value=ICC110
AuthApiKey=ClientKey
AuthApiValue=RydLDE8CFJ
#0*fZ^y5@G2b!pgGQAD9SnP
AuthApiCode=Q2xpZW50S2V5OjAqZlpeeTVARzJiIXBnR1FBRDlTblA=
vehiclePostingReturnLink=https://digigoalliance.com/EwayMotorApi/dispatch/api/covernote/non-life/motor/v2/acknowledge
NonMotorPostingReturnLink=https://digigoalliance.com/EwayMotorApi/dispatch/api/ecovernote/api/covernote/non-life/other/v2/acknowledge
NonMotorPostingV1Link=https://api.tira.go.tz:8091/ecovernote/api/covernote/non-life/other/v2/request
tiraSystemCode=LSYS_ALLIANCE_002
tiraCompanyCode=1CC125
# Product Ids
motor.productId=5
travel.productId=4
building.productId=3
personalaccident.productId=13
workmencompensation.productId=14
employeesliability.productId=15
sme.productId=19

fidelity.productId=32
burglary.productId=1
PremiaBrokerTiraCode=http://localhost:5051/api/gettirabrokercode
PremiaBrokerSPCode=http://localhost:5051/api/getbrokersalepointcode
PremiaBrokerSPCodeAndTiraCode=http://localhost:5051/api/gettiraAndSalePoint


#Basic Auth
ClaimBasicAuthName=claim
ClaimBasicAuthPass=claim123#

#Eway BasicAUth
EwayBasicAuthName=ewayapi
EwayBasicAuthPass=ewayapi123#
SequenceGenerateUrl=http://localhost:8086/api/generatesequence

#spring batch properties
eway.xl.batch.upload=\\\\192.168.1.99\\Users\\CommonPath\\ExcelUpload\\Excel\\
eway.csv.batch.upload=\\\\192.168.1.99\\Users\\CommonPath\\ExcelUpload\\Csv\\
tira.api=http://192.168.1.42:8085/regulatory/showvehicleinfo
save.vehicle.api=http://192.168.1.42:8085/api/savemotordetails
premium.calc.api=http://192.168.1.42:8086/calculator/calc
employee.save.api=http://192.168.1.42:8085/api/saveproductemployees
vehicle.token.api=https://feedback.rtsa.org.zm:9185/api/1.0/auth/authenticate
vehicle.info.api=https://feedback.rtsa.org.zm:9185/api/1.0/vehiclestatus?registrationMark=
spring.batch.job.enabled=false
spring.batch.initialize-schema=always

life.motorapi=http://localhost:8085/
life.commonapi=http://localhost:8086/
server.tomcat.threads.max=200

savemotor=http://localhost:8085/api/savemotordetails
savevehicleinfocall=http://localhost:8085/regulatory/savevehicleinfocall
vehicleFleetPostingReturnLink=https://digigoalliance.com/EwayMotorApi/dispatch/api/covernote/non-life/motor/v2/fleet/acknowledge
mail.pushnotification=https://apps.alliance.co.tz/EwayCommonApi/post/notification/pushnotification
push.tira=http://192.168.1.49:8080/EwayCommonApiLive/payment/pushtira
mptVehicleInfo = http://localhost:8086/api/mtp/validate-vrn
mptVehicleDetails = http://localhost:8086/api/mtp/policy-details

#PremiaPushLink=http://192.168.1.49:8080/EwayCommonApiLive/push/integration/quote
PremiaPushLink=http://localhost:8086/push/integration/quote

#Document Image Validation
DocumentImageValidation =http://139.59.23.162:8009/api/damage/analyze-damage


#Validate Double Insurance
DoubleInsuranceLink =https://api.dmvic.com/api/v6/Integration/ValidateDoubleInsurance 
generateToken=http://192.168.24.14:8086/auth/generateToken
PremiaDoubleInsuranceToken = http://192.168.24.14:8086/common/invokeProcedure
#tokenGeneration =https://api.dmvic.com/api/V1/Account/Login
#PI Integration
clientId=20
integrationKey=CDDFBDA3-FAA3-49CE-8BBB-F3AB831AB70C
integrationReference=FirstAssurance_UAT_PI
firtsAssuranceFile=S:/Santhosh Kumar/Reference/FACL/AKI-PI-FirstAssurance-UAT-2025/FirstassurancePIUAT.pfx
passWord=jtUTJplJRwJmfztx
userName=wluchera@firstassurance.co.ke
userPassWord=PI@2025
kmpdcValidation=https://sandbox-api.dmvic.com/api/v1/pi/integration/ValidateKMPDC
issueProfessionalDoctor=https://sandbox-api.dmvic.com/api/v1/pi/integration/IssueProfessionalDoctor
getCertificate=https://integration.dmvic.com/api/v1/pi/integration/GetCertificate
vehicleSearch=https://api.dmvic.com/api/v6/Integration/VehicleSearch
vehicleCertificate=https://api.dmvic.com/api/v6/Integration/GetCertificate
# Format SQL nicely
#spring.jpa.properties.hibernate.format_sql=true

# Log SQL with timing
#logging.level.org.hibernate.SQL=OFF
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
#logging.level.org.hibernate.engine.jdbc.internal.StatementPreparerImpl=OFF
#logging.level.org.hibernate.engine.jdbc.internal.StatementExecutor=OFF
#spring.jpa.properties.hibernate.generate_statistics=true
#logging.level.org.hibernate.stat=DEBUG

# folder path
#logging.file.path=D:/Log

# log file name
#logging.file.name=D:/Log/motorLog.txt


# application.properties
#spring.jpa.properties.hibernate.jdbc.batch_size=50
#spring.jpa.properties.hibernate.order_inserts=true
#spring.jpa.properties.hibernate.order_updates=true
#spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true


#spring.datasource.hikari.maximum-pool-size=30
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.connection-timeout=30000


#Upr insert 
UprPolicyInsert=http://localhost:8080/api/v1/policies
