/*
 * Java domain class for entity "BankMaster" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
* Created on 2022-08-24 ( 12:58:26 )
* Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/

package com.maan.eway.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.transaction.annotation.Transactional;

import com.maan.eway.bean.EserviceMotorDetails;
import com.maan.eway.bean.EserviceMotorDetailsId;

public interface EServiceMotorDetailsRepository extends JpaRepository<EserviceMotorDetails, EserviceMotorDetailsId>,
		JpaSpecificationExecutor<EserviceMotorDetails> {

	List<EserviceMotorDetails> findByRequestReferenceNoAndIdNumber(String requestReferenceNo, String idNumber);

	List<EserviceMotorDetails> findByRequestReferenceNoAndIdNumberOrderByRiskIdDesc(String requestReferenceNo,
			String idNumber);

	List<EserviceMotorDetails> findByRequestReferenceNo(String requestReferenceNo);

	List<EserviceMotorDetails> findByRequestReferenceNoAndIdNumberAndRiskId(String requestReferenceNo, String idNumber,
			Integer valueOf);

	EserviceMotorDetails findByRequestReferenceNoAndRiskId(String requestReferenceNo, Integer vehId);

	List<EserviceMotorDetails> findByRequestReferenceNoInOrderByUpdatedDateDesc(List<String> reqRefNos);

	List<EserviceMotorDetails> findByRequestReferenceNoOrderByRiskIdAsc(String requestReferenceNo);

	EserviceMotorDetails findByRequestReferenceNoAndChassisNumberOrderByRiskIdAsc(String reqRefNos, String chassisNo);

	List<EserviceMotorDetails> findByRequestReferenceNoOrderByRiskIdDesc(String requestReferenceNo);

	List<EserviceMotorDetails> findByRequestReferenceNoAndStatusNotIn(String requestReferenceNo,
			List<String> statusesNot);

	List<EserviceMotorDetails> findByCompanyIdAndProductIdAndChassisNumber(String companyId, String productId,
			String chassisNumber);

	List<EserviceMotorDetails> findByCompanyIdAndProductIdAndRegistrationNumberAndStatus(String companyId,
			String productId, String registrationnumber, String string);

	@Query(value = """
			SELECT COUNT(1)
			FROM eservice_motor_details
			WHERE request_reference_no = :requestRef
			AND chassis_number = :chassis
			AND risk_id <> :riskId
			""", nativeQuery = true)
	Integer existsDuplicateChassis(
		    String requestRef,
		    String chassis,
		    Integer riskId
		);

	@Query(value = "SELECT sum_insured AS sumInsured, " + "acccessories_sum_insured AS acccessoriesSumInsured, " +"CUSTOMER_ID AS customerId,"
			+ "wind_screen_sum_insured AS windScreenSumInsured, " + "tppd_increae_limit AS tppdIncreaeLimit, "
			+ "non_elec_accessories_si_lc AS nonElecAccessoriesSiLc, " + "excess_limit_lc AS excessLimitLc, "
			+ "exchange_rate AS exchangeRate, " + "currency AS currency, " + "entry_date AS entryDate, " 
			+ "created_by AS createdBy, " + "old_policy_number AS oldPolicyNumber, "+ "QUOTE_NO AS quoteNo " + "FROM eservice_motor_details "
			+ "WHERE request_reference_no = :requestRef AND risk_id = :riskId", nativeQuery = true)
	EServiceMotorDetailsMapper findOldMinimal(@Param("requestRef") String requestRef, @Param("riskId") Integer riskId);

	@Transactional
	@Modifying
	@Query(value = "DELETE FROM eservice_motor_details "
			+ "WHERE request_reference_no = :requestRef AND risk_id = :riskId", nativeQuery = true)
	void deleteByRequestRefAndRiskId(@Param("requestRef") String requestRef, @Param("riskId") Integer riskId);

//	@Query(value = "SELECT " + "sum_insured AS sumInsured, " + "acccessories_sum_insured AS acccessoriesSumInsured, "
//			+ "wind_screen_sum_insured AS windScreenSumInsured, " + "tppd_increae_limit AS tppdIncreaeLimit, "
//			+ "non_elec_accessories_si_lc AS nonElecAccessoriesSiLc, " + "excess_limit_lc AS excessLimitLc, "
//			+ "exchange_rate AS exchangeRate, " + "currency AS currency, " + "entry_date AS entryDate, "
//			+ "created_by AS createdBy, " + "old_policy_number AS oldPolicyNumber " + "FROM eservice_motor_details "
//			+ "WHERE request_reference_no = :requestRef " + "AND risk_id = :riskId", nativeQuery = true)
//	EServiceMotorDetailsMapper findMotorDetailsMinimal(@Param("requestRef") String requestRef,
//			@Param("riskId") Integer riskId);

	@Query(value = "SELECT " + "sum_insured AS sumInsured, " + "acccessories_sum_insured AS acccessoriesSumInsured, "
			+ "wind_screen_sum_insured AS windScreenSumInsured, " + "tppd_increae_limit AS tppdIncreaeLimit, "
			+ "non_elec_accessories_si_lc AS nonElecAccessoriesSiLc, " + "excess_limit_lc AS excessLimitLc, "
			+ "exchange_rate AS exchangeRate, " + "currency AS currency, " + "entry_date AS entryDate, "
			+ "created_by AS createdBy, " + "old_policy_number AS oldPolicyNumber, " + "product_id AS productId, "
			+ "section_id AS sectionId, " + "branch_code AS branchCode, " + "company_id AS companyId, "
			+ "risk_id AS riskId, " + "agency_code AS agencyCode, " + "vd_refno AS vdRefno, " + "cd_refno AS cdRefno, "
			+ "ms_refno AS msRefno, " + "chassis_number AS chassisNumber, " + "status AS status, "
			+ "accident AS accident, " + "gps_tracking_installed AS gpsTrackingInstalled, "
			+ "wind_screen_cover_required AS windScreenCoverRequired, " + "motor_usage AS motorUsage, "
			+ "insurance_class AS insuranceClass, " + "insurance_type AS insuranceType, " + "ncd_yn AS ncdYn, "
			+ "ncd_years AS ncdYears, " + "no_of_claims AS noOfClaims, " + "no_of_compehensives AS noOfCompehensives, "
			+ "no_of_vehicles AS noOfVehicles, " + "owner_category AS ownerCategory, "
			+ "registration_year AS registrationYear, " + "vehicle_type AS vehicleType, "
			+ "tppd_increae_limit_lc AS tppdIncreaeLimitLc, " + "wind_screen_sum_insured_lc AS windScreenSumInsuredLc, "
			+ "acccessories_sum_insured_lc AS acccessoriesSumInsuredLc, "
			+ "wind_screen_sum_insured AS windScreenSumInsured, "
			+ "acccessories_sum_insured AS acccessoriesSumInsured, " + "havepromocode AS havepromocode, "
			+ "promocode AS promocode, " + "endorsement_type AS endorsementType, " + "IS_FINYN  AS isFinaceYn, "
			+ "car_alarm_yn AS carAlarmYn, " + "excess AS excess, " + "credit_shortfall_si AS creditShortfallSi, "
			+ "vehicle_value_type AS vehicleValueType, " + "inflation AS inflation, " + "ncb AS ncb, "
			+ "defence_value AS defenceValue, " + "registration_date AS registrationDate, "
			+ "purchase_date AS purchaseDate, " + "cust_renewal_yn AS custRenewalYn, " + "zone AS zone, "
			+ "horse_power AS horsePower, " + "pa_coverid AS paCoverId, " + "no_of_passengers AS noOfPassengers, "
			+ "cover_id AS coverId, " + "import_yn AS importYN ," + "VEHICLE_MAKE AS vehicleMake , " +"VEHCILE_MODEL as vehcileModel, "
			+"FUEL_TYPE AS fuelType ,"+"MANUFACTURE_YEAR AS manufactureYear ,"+"CITY_LIMIT AS CityLimit ,"+"MANUFACTURE_AGE as manufactureAge,"
					+ "SEATING_CAPACITY AS seatingCapacity , "+"PERIOD_OF_INSURANCE AS periodOfInsurance ,"+"GROSS_WEIGHT AS grossWeight , "
			+"FLEET_OWNER_YN AS fleetOwnerYn ,"+"CLAIM_RATIO as claimRatio "
			+ " FROM eservice_motor_details " + "WHERE request_reference_no = :requestRef "
			+ "AND risk_id = :riskId", nativeQuery = true)
	EServiceMotorDetailsMapper findMotorDetailsMinimal(@Param("requestRef") String requestRef,
			@Param("riskId") Integer riskId);

	@Transactional
	@Modifying
	void deleteByRequestReferenceNoAndRiskId(String requestReferenceNo, Integer riskId);
}
