/*
 * Java domain class for entity "FactorTypeDetails" 
 * Created on 2022-09-30 ( Date ISO 2022-09-30 - Time 18:45:34 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-30 ( 18:45:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.maan.eway.bean.FactorTypeDetails;
import com.maan.eway.bean.FactorTypeDetailsId;
/**
 * <h2>FactorTypeDetailsRepository</h2>
 *
 * createdAt : 2022-09-30 - Time 18:45:34
 * <p>
 * Description: "FactorTypeDetails" Repository
 */
 
 
 
public interface FactorTypeDetailsRepository  extends JpaRepository<FactorTypeDetails,FactorTypeDetailsId > , JpaSpecificationExecutor<FactorTypeDetails> {
	
	@Query("""
		    SELECT f
		    FROM FactorTypeDetails f
		    WHERE f.companyId = :companyId
		      AND f.productId = :productId
		      AND f.amendId = (
		          SELECT MAX(f2.amendId)
		          FROM FactorTypeDetails f2
		          WHERE f2.companyId = f.companyId
		            AND f2.productId = f.productId
		            AND f2.ratingFieldId = f.ratingFieldId
		      )
		""")
		List<FactorTypeDetails> findLatestByCompanyIdAndProductId(
		        @Param("companyId") String companyId,
		        @Param("productId") Integer productId);

}
