/*
 * Java domain class for entity "MsCommonDetails" 
 * Created on 2022-10-19 ( Date ISO 2022-10-19 - Time 17:10:34 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-10-19 ( 17:10:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;
import java.util.List;
import java.util.Set;

import com.maan.eway.bean.MsCommonDetails;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.maan.eway.bean.MsCommonDetailsId;
/**
 * <h2>MsCommonDetailsRepository</h2>
 *
 * createdAt : 2022-10-19 - Time 17:10:34
 * <p>
 * Description: "MsCommonDetails" Repository
 */
 
 
 
public interface MsCommonDetailsRepository  extends JpaRepository<MsCommonDetails,MsCommonDetailsId > , JpaSpecificationExecutor<MsCommonDetails> {

	
	MsCommonDetails findByCdRefnoAndVdRefno(Long valueOf, Long valueOf2);

	MsCommonDetails findByMsRefno(Long msrefno);

	MsCommonDetails findByCdRefnoAndVdRefnoAndRequestreferenceno(Long valueOf, Long valueOf2,
			String requestReferenceNo);

	MsCommonDetails findByCdRefnoAndVdRefnoAndRequestreferencenoAndAgencyCodeAndBranchCodeAndInsuranceIdAndProductIdAndSectionIdAndStatus(
			Long valueOf, Long valueOf2, String requestReferenceNo,String agencyCode,String branchCode,String insuranceId,Integer  productId,Integer sectionId,String status);

	MsCommonDetails findByCdRefnoAndVdRefnoAndRequestreferencenoAndStatus(Long valueOf, Long valueOf2,
			String requestReferenceNo, String string);

	MsCommonDetails findByCdRefnoAndVdRefnoAndRequestreferencenoAndAgencyCodeAndBranchCodeAndInsuranceIdAndProductIdAndSectionIdAndStatusAndDdRefno(
			Long valueOf, Long valueOf2, String requestReferenceNo, String agencyCode, String branchCode,
			String companyId, Integer valueOf3, Integer valueOf4, String string, Long ddRefno);

	

	List<MsCommonDetails> findByRequestreferencenoAndSectionIdAndProductIdAndLocationId(String requestRefNo,
			Integer section, Integer product, Integer locationId);

	List<MsCommonDetails> findByRequestreferencenoAndLocationId(String requestReferenceNo, Integer locId);

	List<MsCommonDetails> findByRequestreferencenoAndLocationIdAndSectionIdIn(String requestReferenceNo, Integer locId,
			Set<Integer> sectionin);

	List<MsCommonDetails> findByRequestreferencenoAndProductIdAndLocationId(String requestRefNo, Integer product,
			Integer locationId);

	long deleteByRequestreferencenoAndLocationId(String requestReferenceNo, Integer locId);

	long deleteByRequestreferencenoAndLocationIdAndSectionIdIn(String requestReferenceNo, Integer locId,
			Set<Integer> sectionin);

	long deleteByRequestreferencenoAndLocationIdIn(String requestReferenceNo, Set<Integer> locId);

	
	/*
	 * 
	 *  private String     insuranceId ;
    
    private String     branchCode ;
    
    private String     agencyCode ;
    
    private Integer    sectionId ;
    
    private Integer    productId ;
    
    private Long       cdRefno ;
    
    private Long       msRefno ;
    
    private String     requestreferenceno ;
    
    private String     status ;
    
    private Long       vdRefno ;*/

}
