/*
 * Java domain class for entity "MsCustomerDetails" 
 * Created on 2022-10-19 ( Date ISO 2022-10-19 - Time 17:10:34 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-10-19 ( 17:10:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.maan.eway.bean.MsCustomerDetails;
import com.maan.eway.bean.MsCustomerDetailsId;
/**
 * <h2>MsCustomerDetailsRepository</h2>
 *
 * createdAt : 2022-10-19 - Time 17:10:34
 * <p>
 * Description: "MsCustomerDetails" Repository
 */
 
 
 
public interface MsCustomerDetailsRepository  extends JpaRepository<MsCustomerDetails,MsCustomerDetailsId > , JpaSpecificationExecutor<MsCustomerDetails> {

	
	List<MsCustomerDetails> findByIdNumber(String idNumber);

	MsCustomerDetails findByCdRefno(Long valueOf);
	
	@Query(value = "SELECT * FROM ms_customer_details WHERE " +
	        "LOWER(policy_holder_typeid) = LOWER(:policyHolderTypeid) AND " +
	        "LOWER(policy_holder_type) = LOWER(:policyHolderType) AND " +

	        // age handling
	        "((:age IS NULL AND age IS NULL) OR age = :age) AND " +

	        "LOWER(gender) = LOWER(:gender) AND " +

	        // occupation handling
	        "((:occupation IS NULL AND occupation IS NULL) OR LOWER(occupation) = LOWER(:occupation)) AND " +

	        "LOWER(region_code) = LOWER(:regionCode) AND " +
	        "LOWER(status) = LOWER(:status) AND " +
	        "LOWER(id_number) = LOWER(:idNumber) AND " +

	        // taxExemptedId handling
	        "((:taxExemptedId IS NULL AND tax_exempted_id IS NULL) OR tax_exempted_id = :taxExemptedId) " +

	        "LIMIT 1",
	        nativeQuery = true)
	Optional<MsCustomerDetails> findMatchingCustomerFast(
	        @Param("policyHolderTypeid") String policyHolderTypeid,
	        @Param("policyHolderType") String policyHolderType,
	        @Param("age") Integer age,
	        @Param("gender") String gender,
	        @Param("occupation") String occupation,
	        @Param("status") String status,
	        @Param("idNumber") String idNumber,
	        @Param("taxExemptedId") String taxExemptedId,
	        @Param("regionCode") String regionCode
	);
}
