/*
 * Java domain class for entity "MsVehicleDetails" 
 * Created on 2022-10-19 ( Date ISO 2022-10-19 - Time 17:10:35 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
* Created on 2022-10-19 ( 17:10:35 )
* Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/

package com.maan.eway.repository;

import java.util.Date;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.maan.eway.bean.MsVehicleDetails;
import com.maan.eway.bean.MsVehicleDetailsId;

/**
 * <h2>MsVehicleDetailsRepository</h2>
 *
 * createdAt : 2022-10-19 - Time 17:10:35
 * <p>
 * Description: "MsVehicleDetails" Repository
 */

public interface MsVehicleDetailsRepository
		extends JpaRepository<MsVehicleDetails, MsVehicleDetailsId>, JpaSpecificationExecutor<MsVehicleDetails> {

	List<MsVehicleDetails> findByChassisNumber(String chassisNumber);

	MsVehicleDetails findByVdRefno(Long valueOf);

	List<MsVehicleDetails> findByChassisNumberAndRequestReferenceNoAndMotorUsageAndInsuranceTypeAndGpsYnAndNcdYnAndInsuranceClassAndEntryDateBetween(
			String chassisNumber, String requestReferenceNo, String motorUsage, String insuranceType, String gpsYn,
			String ncdYn, String insuranceClass, Date startDate, Date endDate);

	@Query("""
			    SELECT m.vdRefno AS vdRefno,
			           m.locationId AS locationId,
			           m.vehicleId AS vehicleId,
			           m.status AS status
			    FROM MsVehicleDetails m
			    WHERE m.chassisNumber = :chassisNumber
			      AND m.requestReferenceNo = :requestReferenceNo
			      AND m.motorUsage = :motorUsage
			      AND m.insuranceType = :insuranceType
			      AND m.gpsYn = :gpsYn
			      AND m.ncdYn = :ncdYn
			      AND m.insuranceClass = :insuranceClass
			      AND m.entryDate BETWEEN :startDate AND :endDate
			""")
	List<MsVehicleMinimal> findMinimalVehicles(@Param("chassisNumber") String chassisNumber,
			@Param("requestReferenceNo") String requestReferenceNo, @Param("motorUsage") String motorUsage,
			@Param("insuranceType") String insuranceType, @Param("gpsYn") String gpsYn, @Param("ncdYn") String ncdYn,
			@Param("insuranceClass") String insuranceClass, @Param("startDate") Date startDate,
			@Param("endDate") Date endDate);

}
