/*
 * Java domain class for entity "SectionCoverMaster" 
 * Created on 2022-09-30 ( Date ISO 2022-09-30 - Time 18:45:44 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-30 ( 18:45:44 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.repository.query.Param;

import com.maan.eway.bean.SectionCoverMaster;
import com.maan.eway.bean.SectionCoverMasterId;
/**
 * <h2>SectionCoverMasterRepository</h2>
 *
 * createdAt : 2022-09-30 - Time 18:45:44
 * <p>
 * Description: "SectionCoverMaster" Repository
 */
 
 
 
public interface SectionCoverMasterRepository  extends JpaRepository<SectionCoverMaster,SectionCoverMasterId > , JpaSpecificationExecutor<SectionCoverMaster> {

	
	SectionCoverMaster findTopByCompanyIdAndProductIdAndSectionIdAndStatusAndCoverIdOrderByAmendIdDesc(String companyId,
			Integer productId, Integer sectionId, String string, Integer cover);

	SectionCoverMaster findTopByCompanyIdAndProductIdAndSectionIdAndStatusInAndCoverIdOrderByAmendIdDesc(String companyId, Integer productId, Integer sectionId, List<String> status, Integer cover);

	@Query("SELECT s FROM SectionCoverMaster s WHERE s.companyId = :companyId AND s.productId = :productId AND s.sectionId = :sectionId AND s.status IN :status AND s.coverId IN :cover AND s.amendId = (SELECT MAX(s2.amendId) FROM SectionCoverMaster s2 WHERE s2.coverId = s.coverId AND s2.companyId = :companyId AND s2.productId = :productId AND s2.sectionId = :sectionId AND s2.status IN :status)")
	List<SectionCoverMaster> findLatestAmendPerCover(@Param("companyId") String companyId,@Param("productId") Integer productId,@Param("sectionId") Integer sectionId, @Param("status") List<String> status,@Param("cover") Set<Integer> cover);

	List<SectionCoverMaster> findByCompanyIdAndProductIdAndSectionIdAndStatusInAndCoverIdInOrderByAmendIdDesc(
			String companyId, Integer productId, Integer sectionId, List<String> status, List<Integer> cover);

	List<SectionCoverMaster> findByCompanyIdAndProductIdAndSectionIdAndStatusInOrderByAmendIdDesc(String companyId,
			Integer productId, Integer sectionId, List<String> status);

}
