/*
 * Java domain class for entity "MsCommonDetails" 
 * Created on 2022-10-19 ( Date ISO 2022-10-19 - Time 17:10:34 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.res;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "MsCommonDetails"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class MsCommonDetailsRes implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Insuranceid")
    private String     insuranceId  ;
	@JsonProperty("Branchcode")
    private String     branchCode   ;
	@JsonProperty("Agencycode")
    private String     agencyCode   ;
	@JsonProperty("Sectionid")
    private Integer    sectionId    ;
	@JsonProperty("Productid")
    private Integer    productId    ;
	@JsonProperty("Cdrefno")
    private Long       cdRefno      ;
	@JsonProperty("Msrefno")
    private Long       msRefno      ;
	@JsonProperty("Requestreferenceno")
    private String     requestreferenceno ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Param1")
	private String param1;
	@JsonProperty("Param2")
	private String param2;
	@JsonProperty("Param3")
	private String param3;
	@JsonProperty("Param4")
	private String param4;
	@JsonProperty("Param5")
	private String param5;
	@JsonProperty("Param6")
	private String param6;
	@JsonProperty("Param7")
	private String param7;
	@JsonProperty("Param8")
	private String param8;
	@JsonProperty("Param9")
	private String param9;
	@JsonProperty("Param10")
	private String param10;
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Entrydate")
    private Date       entryDate    ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
