/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-06-19 ( Date ISO 2024-06-19 - Time 16:50:51 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-06-19 ( 16:50:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.eway.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "BuildingRiskDetails"
 *
 * @author Telosys Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(BuildingRiskDetailsId.class)
@Table(name = "building_risk_details")

public class BuildingRiskDetails implements Serializable {

	private static final long serialVersionUID = 1L;

	//=========================================
    @Id
    @Column(name = "REQUEST_REFERENCE_NO", length = 20, nullable = false)
    private String requestReferenceNo;

    @Id
    @Column(name = "QUOTE_NO", length = 20, nullable = false)
    private String quoteNo;

    @Id
    @Column(name = "LOCATION_ID", nullable = false)
    private Integer locationId;

    @Id
    @Column(name = "RISK_ID", nullable = false)
    private Integer riskId;

    @Id
    @Column(name = "SECTION_ID", length = 20, nullable = false)
    private String sectionId;

    @Id
    @Column(name = "COVER_ID")
    private Integer coverId;

    // Columns
    @Column(name = "POLICY_NO", length = 100)
    private String policyNo;

    @Column(name = "LOCATION_NAME", length = 200)
    private String locationName;

    @Column(name = "DOMESTIC_PACKAGE_YN", length = 20)
    private String domesticPackageYn;

    @Column(name = "PRODUCT_ID", length = 20)
    private String productId;

    @Column(name = "PRODUCT_DESC", length = 100)
    private String productDesc;

    @Column(name = "SECTION_DESC", length = 100)
    private String sectionDesc;

    @Column(name = "COMPANY_ID", length = 20)
    private String companyId;

    @Column(name = "COMPANY_NAME", length = 100)
    private String companyName;

    @Column(name = "BRANCH_CODE", length = 20)
    private String branchCode;

    @Column(name = "BRANCH_NAME", length = 100)
    private String branchName;

    @Column(name = "APPLICATION_ID", length = 20)
    private String applicationId;

    @Column(name = "BROKER_CODE", length = 20)
    private String brokerCode;

    @Column(name = "SUB_USER_TYPE", length = 30)
    private String subUserType;

    @Column(name = "AGENCY_CODE", length = 20)
    private String agencyCode;

    @Column(name = "LOGIN_ID", length = 100)
    private String loginId;

    @Column(name = "BROKER_BRANCH_CODE", length = 20)
    private String brokerBranchCode;

    @Column(name = "BROKER_BRANCH_NAME", length = 100)
    private String brokerBranchName;

    @Column(name = "SOURCE_TYPE", length = 100)
    private String sourceType;

    @Column(name = "AC_EXECUTIVE_ID")
    private Integer acExecutiveId;

    @Column(name = "BDM_CODE", length = 100)
    private String bdmCode;

    @Column(name = "CUSTOMER_CODE", length = 100)
    private String customerCode;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "POLICY_START_DATE")
    private Date policyStartDate;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "POLICY_END_DATE")
    private Date policyEndDate;

    @Column(name = "POLICY_PERIORD")
    private Integer policyPeriod;

    @Column(name = "CURRENCY", length = 20)
    private String currency;

    @Column(name = "EXCHANGE_RATE")
    private BigDecimal exchangeRate;

    @Column(name = "HAVEPROMOCODE", length = 10)
    private String havePromoCode;

    @Column(name = "PROMOCODE", length = 100)
    private String promoCode;

    @Column(name = "INBUILD_CONSTRUCT_TYPE", length = 20)
    private String inbuildConstructType;

    @Column(name = "BUILDING_FLOORS")
    private Integer buildingFloors;

    @Column(name = "OUTBUILD_CONSTRUCT_TYPE", length = 20)
    private String outbuildConstructType;

    @Column(name = "BUILDING_USAGE_YN", length = 2)
    private String buildingUsageYn;

    @Column(name = "BUILDING_USAGE_ID", length = 100)
    private String buildingUsageId;

    @Column(name = "BUILDING_USAGE_DESC", length = 100)
    private String buildingUsageDesc;

    @Column(name = "BUILDING_OWNER_YN", length = 20)
    private String buildingOwnerYn;

    @Column(name = "BUILDING_TYPE", length = 100)
    private String buildingType;

    @Column(name = "BUILDING_OCCUPATION_TYPE", length = 100)
    private String buildingOccupationType;

    @Column(name = "BUILDING_CONDITION", length = 100)
    private String buildingCondition;

    @Column(name = "BUILDING_AGE")
    private Integer buildingAge;

    @Column(name = "BUILDING_AREA_SQM")
    private BigDecimal buildingAreaSqm;

    @Column(name = "INSURANCE_TYPE", length = 100)
    private String insuranceType;

    @Column(name = "OCCUPATION_TYPE", length = 20)
    private String occupationType;

    @Column(name = "OCCUPATION_TYPE_DESC", length = 100)
    private String occupationTypeDesc;

    @Column(name = "CATEGORY_ID", length = 20)
    private String categoryId;

    @Column(name = "CATEGORY_DESC", length = 100)
    private String categoryDesc;

    @Column(name = "INDUSTRY_ID")
    private Integer industryId;

    @Column(name = "INDUSTRY_DESC", length = 100)
    private String industryDesc;

    @Column(name = "WALL_TYPE", length = 20)
    private String wallType;

    @Column(name = "WALL_TYPE_DESC", length = 100)
    private String wallTypeDesc;

    @Column(name = "ROOF_TYPE", length = 20)
    private String roofType;

    @Column(name = "ROOF_TYPE_DESC", length = 100)
    private String roofTypeDesc;

    @Column(name = "NATURE_OF_TRADE_ID")
    private Integer natureOfTradeId;

    @Column(name = "NATURE_OF_TRADE_DESC", length = 100)
    private String natureOfTradeDesc;

    @Column(name = "INSURANCE_FOR_ID", length = 100)
    private String insuranceForId;

    @Column(name = "INSURANCE_FOR_DESC", length = 100)
    private String insuranceForDesc;

    @Column(name = "INTERNAL_WALL_TYPE")
    private Integer internalWallType;

    @Column(name = "INTERNAL_WALL_DESC", length = 100)
    private String internalWallDesc;

    @Column(name = "CEILING_TYPE")
    private Integer ceilingType;

    @Column(name = "CEILING_TYPE_DESC", length = 100)
    private String ceilingTypeDesc;

    @Column(name = "ADDRESS", length = 300)
    private String address;

    @Column(name = "OCCUPIED_YEAR")
    private Integer occupiedYear;

    @Column(name = "FIRST_LOSS_PERCENT")
    private Long firstLossPercent;

    @Column(name = "MAKUTI_YN", length = 10)
    private String makutiYn;

    @Column(name = "INDEMITY_PERIOD", length = 10)
    private String indemnityPeriod;

    @Column(name = "INDEMITY_PERIOD_DESC", length = 100)
    private String indemnityPeriodDesc;

    @Column(name = "PLATE_GLASS_TYPE", length = 10)
    private String plateGlassType;

    @Column(name = "PLATE_GLASS_DESC", length = 100)
    private String plateGlassDesc;

    @Column(name = "CUSTOMER_NAME", length = 100)
    private String customerName;

    @Column(name = "INDEMNITY_PERIOD_LC")
    private BigDecimal indemnityPeriodLc;

    @Column(name = "INDEMNITY_PERIOD_FC")
    private BigDecimal indemnityPeriodFc;

    @Column(name = "GROSS_PROFIT_LC")
    private BigDecimal grossProfitLc;

    @Column(name = "GROSS_PROFIT_FC")
    private BigDecimal grossProfitFc;

    @Column(name = "TRANSPORTED_BY", length = 30)
    private String transportedBy;

    @Column(name = "MODE_OF_TRANSPORT", length = 30)
    private String modeOfTransport;

    @Column(name = "GEOGRAPHICAL_COVERAGE", length = 30)
    private String geographicalCoverage;

    @Column(name = "BOND_TYPE", length = 20)
    private String bondType;

    @Column(name = "BOND_YEAR", length = 20)
    private String bondYear;

    @Column(name = "Content_id", length = 20)
    private String contentId;

    @Column(name = "CONTENT_DESC", length = 2000)
    private String contentDesc;

    @Column(name = "serial_no", length = 200)
    private String serialNo;

    @Column(name = "FIRST_LOSS_PAYEE", length = 50)
    private String firstLossPayee;

    @Column(name = "SUM_INSURED")
    private BigDecimal sumInsured;

    @Column(name = "SUM_INSURED_LC")
    private BigDecimal sumInsuredLc;

    @Column(name = "COLLATERAL_YN", length = 50)
    private String collateralYn;

    @Column(name = "COLLATERAL_NAME", length = 100)
    private String collateralName;

    @Column(name = "BORROWER_TYPE", length = 100)
    private String borrowerType;

    @Column(name = "BORROWER_TYPE_DESC", length = 100)
    private String borrowerTypeDesc;

    @Column(name = "NO_OF_CLAIM")
    private Integer noOfClaim;

    @Column(name = "NO_OF_CLAIM_DESC", length = 100)
    private String noOfClaimDesc;

    @Column(name = "NO_OF_MONTHS_CONSTRUCTION")
    private Integer noOfMonthsConstruction;

    @Column(name = "PARAM1", length = 100)
    private String param1;

    @Column(name = "PARAM2", length = 100)
    private String param2;

    @Column(name = "PARAM3", length = 100)
    private String param3;

    @Column(name = "PARAM4", length = 100)
    private String param4;

    @Column(name = "PARAM5", length = 100)
    private String param5;

    @Column(name = "PARAM6", length = 100)
    private String param6;

    @Column(name = "PARAM7", length = 100)
    private String param7;

    @Column(name = "PARAM8", length = 100)
    private String param8;

    @Column(name = "PARAM9", length = 100)
    private String param9;

    @Column(name = "PARAM10", length = 100)
    private String param10;

    @Column(name = "PARAM11", length = 100)
    private String param11;

    @Column(name = "PARAM12", length = 100)
    private String param12;

    @Column(name = "PARAM13", length = 100)
    private String param13;

    @Column(name = "PARAM14", length = 100)
    private String param14;

    @Column(name = "PARAM15", length = 100)
    private String param15;

    @Column(name = "COMMISSION_TYPE", length = 20)
    private String commissionType;

    @Column(name = "COMMISSION_TYPE_DESC", length = 100)
    private String commissionTypeDesc;

    @Column(name = "MANUAL_REFERAL_YN", length = 100)
    private String manualReferalYn;

    @Column(name = "ADMIN_LOGIN_ID", length = 100)
    private String adminLoginId;

    @Column(name = "ADMIN_REMARKS", length = 1000)
    private String adminRemarks;

    @Column(name = "REJECT_REASON", length = 1000)
    private String rejectReason;

    @Column(name = "Referal_Remarks", length = 500)
    private String referalRemarks;

    @Column(name = "FINALIZE_YN", length = 2)
    private String finalizeYn;

    @Column(name = "REGION_CODE", length = 20)
    private String regionCode;

    @Column(name = "REGION_DESC", length = 100)
    private String regionDesc;

    @Column(name = "DISTRICT_CODE", length = 20)
    private String districtCode;

    @Column(name = "DISTRICT_DESC", length = 100)
    private String districtDesc;

    @Column(name = "TIRA_COVER_NOTE_NO", length = 100)
    private String tiraCoverNoteNo;

    @Column(name = "COMMISSION_PERCENTAGE")
    private BigDecimal commissionPercentage;

    @Column(name = "VAT_COMMISSION")
    private BigDecimal vatCommission;

    @Column(name = "BROKER_TIRA_CODE", length = 100)
    private String brokerTiraCode;

    @Column(name = "SOURCE_TYPE_ID", length = 20)
    private String sourceTypeId;

    @Column(name = "VD_REFNO")
    private Long vdRefno;

    @Column(name = "CD_REFNO")
    private Long cdRefno;

    @Column(name = "MS_REFNO")
    private Long msRefno;

    @Column(name = "SALE_POINT_CODE", length = 200)
    private String salePointCode;

    @Column(name = "OTHER_OCCUPATION", length = 200)
    private String otherOccupation;

    @Column(name = "COVERING_DETAILS", length = 1000)
    private String coveringDetails;

    @Column(name = "DESCRIPTION_OF_RISK", length = 1000)
    private String descriptionOfRisk;

    @Column(name = "CUSTOMER_ID", length = 20)
    private String customerId;

    @Column(name = "ACTUAL_PREMIUM_FC")
    private BigDecimal actualPremiumFc;

    @Column(name = "ACTUAL_PREMIUM_LC")
    private BigDecimal actualPremiumLc;

    @Column(name = "OVERALL_PREMIUM_FC")
    private BigDecimal overallPremiumFc;

    @Column(name = "OVERALL_PREMIUM_LC")
    private BigDecimal overallPremiumLc;

    @Column(name = "OLD_REQ_REF_NO", length = 100)
    private String oldReqRefNo;

    @Column(name = "VAT_PREMIUM")
    private BigDecimal vatPremium;

    @Column(name = "ENDT_VAT_PREMIUM")
    private BigDecimal endtVatPremium;

    @Column(name = "BANK_CODE", length = 100)
    private String bankCode;

    @Column(name = "ENDORSEMENT_TYPE")
    private Integer endorsementType;

    @Column(name = "ENDORSEMENT_TYPE_DESC", length = 100)
    private String endorsementTypeDesc;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ENDORSEMENT_DATE")
    private Date endorsementDate;

    @Column(name = "ENDORSEMENT_REMARKS", length = 100)
    private String endorsementRemarks;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ENDORSEMENT_EFFDATE")
    private Date endorsementEffdate;

    @Column(name = "ORIGINAL_POLICY_NO", length = 100)
    private String originalPolicyNo;

    @Column(name = "ENDT_PREV_POLICY_NO", length = 100)
    private String endtPrevPolicyNo;

    @Column(name = "ENDT_PREV_QUOTE_NO", length = 100)
    private String endtPrevQuoteNo;

    @Column(name = "ENDT_COUNT")
    private BigDecimal endtCount;

    @Column(name = "ENDT_STATUS", length = 10)
    private String endtStatus;

    @Column(name = "IS_FINYN", length = 10)
    private String isFinyn;

    @Column(name = "ENDT_CATEG_DESC", length = 100)
    private String endtCategDesc;

    @Column(name = "ENDT_PREMIUM")
    private BigDecimal endtPremium;

    @Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENTRY_DATE")
    private Date entryDate;

    @Column(name = "CREATED_BY", length = 100)
    private String createdBy;

    @Column(name = "STATUS", length = 2)
    private String status;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_DATE")
    private Date updatedDate;

    @Column(name = "UPDATED_BY", length = 100)
    private String updatedBy;
    
    @Column(name = "BDM_NAME")
   	private String bdmName;
    
    @Column(name = "COUNT")
    private String count;

    
	 
}
