/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-06-19 ( Date ISO 2024-06-19 - Time 16:53:22 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-06-19 ( 16:53:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.eway.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "MsAssetDetails"
 *
 * @author Telosys Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(MsAssetDetailsId.class)
@Table(name = "ms_asset_details")

public class MsAssetDetails implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- PRIMARY KEY FIELDS
    @Id
    @Column(name = "VD_REFNO")
    private Long vdRefno;

    @Id
    @Column(name = "REQUEST_REFERENCE_NO", length = 60)
    private String requestReferenceNo;

    @Id
    @Column(name = "LOCATION_ID")
    private Integer locationId;

    @Id
    @Column(name = "RISK_ID")
    private Integer riskId;

    @Id
    @Column(name = "PRODUCT_ID")
    private Integer productId;

    @Id
    @Column(name = "SECTION_ID")
    private Integer sectionId;

    @Id
    @Column(name = "COVER_ID")
    private Integer coverId;

    @Id
    @Column(name = "COMPANY_ID", length = 60)
    private String companyId;

    @Id
    @Column(name = "BRANCH_CODE", length = 60)
    private String branchCode;

    @Id
    @Column(name = "ENDT_TYPE_ID")
    private Integer endtTypeId;

    @Id
    @Column(name = "ENDT_CATEGORY_ID", length = 300)
    private String endtCategoryId;

    // --- DATA FIELDS
    @Column(name = "CURRENCY", length = 60)
    private String currency;
    
    @Column(name="PERIOD_OF_INSURANCE", nullable=false, length=10)
    private String periodOfInsurance ;
    
    @Column(name="GROUP_COUNT") 
    private Integer groupCount;

    @Column(name = "EXCHANGE_RATE")
    private BigDecimal exchangeRate;

    @Column(name = "HAVEPROMOCODE", length = 30)
    private String havepromocode;

    @Column(name = "PROMOCODE", length = 300)
    private String promocode;

    @Column(name = "INBUILD_CONSTRUCT_TYPE", length = 60)
    private String inbuildConstructType;

    @Column(name = "BUILDING_FLOORS")
    private Integer buildingFloors;

    @Column(name = "BUILDING_USAGE_ID", length = 300)
    private String buildingUsageId;

    @Column(name = "BUILDING_AGE")
    private Integer buildingAge;

    @Column(name = "OCCUPATION_TYPE", length = 60)
    private String occupationType;

    @Column(name = "CATEGORY_ID", length = 60)
    private String categoryId;

    @Column(name = "INDUSTRY_ID")
    private Integer industryId;

    @Column(name = "WALL_TYPE", length = 60)
    private String wallType;

    @Column(name = "ROOF_TYPE", length = 60)
    private String roofType;

    @Column(name = "INTERNAL_WALL_TYPE")
    private Integer internalWallType;

    @Column(name = "FIRST_LOSS_PERCENT")
    private Long firstLossPercent;

    @Column(name = "INSURANCE_CLASS", length = 30)
    private String insuranceClass;

    @Column(name = "INDEMITY_PERIOD", length = 30)
    private String indemityPeriod;

    @Column(name = "INDEMNITY_PERIOD_LC")
    private Double indemnityPeriodLc;

    @Column(name = "INDEMNITY_PERIOD_FC")
    private Double indemnityPeriodFc;

    @Column(name = "GROSS_PROFIT_LC")
    private Double grossProfitLc;

    @Column(name = "GROSS_PROFIT_FC")
    private Double grossProfitFc;

    @Column(name = "TRANSPORTED_BY", length = 90)
    private String transportedBy;

    @Column(name = "MODE_OF_TRANSPORT", length = 90)
    private String modeOfTransport;

    @Column(name = "GEOGRAPHICAL_COVERAGE", length = 90)
    private String geographicalCoverage;

    @Column(name = "BOND_TYPE", length = 60)
    private String bondType;

    @Column(name = "BOND_YEAR", length = 60)
    private String bondYear;

    @Column(name = "CONTENT_ID", length = 60)
    private String contentId;

    @Column(name = "SUM_INSURED")
    private BigDecimal sumInsured;

    @Column(name = "SUM_INSURED_LC")
    private BigDecimal sumInsuredLc;

    @Column(name = "NO_OF_CLAIM")
    private Integer noOfClaim;

    @Column(name = "NO_OF_MONTHS_CONSTRUCTION")
    private Integer noOfMonthsConstruction;

    @Column(name = "PARAM1", length = 300)
    private String param1;

    @Column(name = "PARAM2", length = 300)
    private String param2;

    @Column(name = "PARAM3", length = 300)
    private String param3;

    @Column(name = "PARAM4", length = 300)
    private String param4;

    @Column(name = "PARAM5", length = 300)
    private String param5;

    @Column(name = "PARAM6", length = 300)
    private String param6;

    @Column(name = "PARAM7", length = 300)
    private String param7;

    @Column(name = "PARAM8", length = 300)
    private String param8;

    @Column(name = "PARAM9", length = 300)
    private String param9;

    @Column(name = "PARAM10", length = 300)
    private String param10;

    @Column(name = "PARAM11", length = 300)
    private String param11;

    @Column(name = "PARAM12", length = 300)
    private String param12;

    @Column(name = "PARAM13", length = 300)
    private String param13;

    @Column(name = "PARAM14", length = 300)
    private String param14;

    @Column(name = "PARAM15", length = 300)
    private String param15;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ENTRY_DATE")
    private Date entryDate;

    @Column(name = "CREATED_BY", length = 300)
    private String createdBy;

    @Column(name = "STATUS", length = 6)
    private String status;
}
